# Generated by Django 4.2.3 on 2023-07-16 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'dynamic_table',
            },
        ),
        migrations.CreateModel(
            name='DynamicTableModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dynamic_fields', models.JSONField(default=dict)),
                ('dynamic_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dynamic_rows', to='core.dynamictable')),
            ],
            options={
                'db_table': 'dynamic_model',
            },
        ),
        migrations.CreateModel(
            name='DynamicField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=255)),
                ('field_type', models.CharField(choices=[('string', 'String'), ('number', 'Number'), ('boolean', 'Boolean')], max_length=255)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='core.dynamictable')),
            ],
            options={
                'db_table': 'dynamic_field',
            },
        ),
    ]
